name: Deploy em produção

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_prod
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "source ~/.nvm/nvm.sh; cd ~/server/; ./update.sh; ./deploy.sh cadastro-organico-rural; exit"
          host: cor.agr.br
          username: root
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          CI: true
